### ISSUE TITLE
Button Radio 

### ISSUE THREAD

**Issue by nrjgab** [josh-tf/fxcommands#13]
Hello, my button /setfrequency not working, can you help me please

**Comment by josh-tf** [comment]
Hi mate, `/setfrequency` will only work if it is a command that the server owner has created, you will need to check with them to see if its available

**Comment by macgyverK9** [comment]
Yep I have it t /changeradio 918Sent from my Galaxy
-------- Original message --------From: Josh Bowden ***@***.***> Date: 2023-02-14  8:23 p.m.  (GMT-05:00) To: EggRP/fxcommands ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [EggRP/fxcommands] Button Radio  (Issue #13) 
Hi mate, /setfrequency will only work if it is a command that the server owner has created, you will need to check with them to see if its available

**Comment by nrjgab** [comment]
Ok, I tried the right order, and it still doesn't work

Le mer. 15 févr. 2023, 02:23, Josh Bowden ***@***.***> a
écrit :

**Comment by R4K0** [comment]
The issue is, what we found through a quick debug session - Is that server-side only commands aren't able to be triggered directly through an external plugin call into the console.

If the command was registered on the client, you will be able to trigger it with the plug-in

One work-around around the issue is creating a multi-action step:

1. Create a RunCommand action, that runs `bind keyboard F7 "changeradio 918"`
3. Hotkey - Press F7
4. RunCommand action - `unbind keyboard F7`

Bit arse we have to do that, I'd love being able to avoid this. I'm not sure how the plugin hooks onto the FiveM instance so it can issue commands directly to the console, but perhaps there's another way?
